version: 2

models:
  - name: stg_green_tripdata
    description: "Staging model for Green Taxi trip data"
    columns:
      - name: vendor_id
        data_type: integer
        description: "A code indicating the LPEP provider that provided the record (1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.)."

      - name: rate_code_id
        data_type: integer
        description: "The final rate code in effect at the end of the trip (1= Standard rate, 2=JFK, 3=Newark, 4=Nassau or Westchester, 5=Negotiated fare, 6=Group ride)."

      - name: pickup_location_id
        data_type: integer
        description: "TLC Taxi Zone in which the taximeter was engaged."

      - name: dropoff_location_id
        data_type: integer
        description: "TLC Taxi Zone in which the taximeter was disengaged."

      - name: pickup_datetime
        data_type: timestamp
        description: "The date and time when the meter was engaged."

      - name: dropoff_datetime
        data_type: timestamp
        description: "The date and time when the meter was disengaged."

      - name: store_and_fwd_flag
        data_type: varchar
        description: "This flag indicates whether the trip record was held in vehicle memory before sending to the vendor (Y=store and forward, N=not a store and forward trip)."

      - name: passenger_count
        data_type: integer
        description: "The number of passengers in the vehicle. This is a driver-entered value."

      - name: trip_distance
        data_type: decimal(18,3)
        description: "The elapsed trip distance in miles reported by the taximeter."

      - name: trip_type
        data_type: integer
        description: "A code indicating whether the trip was a street-hail or a dispatch (1= Street-hail, 2= Dispatch)."

      - name: fare_amount
        data_type: decimal(18,3)
        description: "The time-and-distance fare calculated by the meter."

      - name: extra
        data_type: decimal(18,3)
        description: "Miscellaneous extras and surcharges (e.g. $0.50 and $1 rush hour and overnight charges)."

      - name: mta_tax
        data_type: decimal(18,3)
        description: "$0.50 MTA tax that is automatically triggered based on the metered rate in use."

      - name: tip_amount
        data_type: decimal(18,3)
        description: "Tip amount – This field is automatically populated for credit card payments. Cash tips are not included."

      - name: tolls_amount
        data_type: decimal(18,3)
        description: "Total amount of all tolls paid in trip."

      - name: ehail_fee
        data_type: decimal(18,3)
        description: "Fee charged for using the e-hail service."

      - name: improvement_surcharge
        data_type: decimal(18,3)
        description: "$0.30 improvement surcharge assessed on hailed trips at the point of initial hire."

      - name: total_amount
        data_type: decimal(18,3)
        description: "The total amount charged to passengers. Does not include cash tips."

      - name: payment_type
        data_type: integer
        description: "A numeric code signifying how the passenger paid for the trip (1= Credit card, 2= Cash, 3= No charge, 4= Dispute, 5= Unknown, 6= Voided trip)."

  - name: stg_yellow_tripdata
    description: "Staging model for Yellow Taxi trip data"
    columns:
      - name: vendor_id
        data_type: integer
        description: "A code indicating the TPEP provider that provided the record (1= Creative Mobile Technologies, LLC; 2= VeriFone Inc.)."

      - name: rate_code_id
        data_type: integer
        description: "The final rate code in effect at the end of the trip."

      - name: pickup_location_id
        data_type: integer
        description: "TLC Taxi Zone in which the taximeter was engaged."

      - name: dropoff_location_id
        data_type: integer
        description: "TLC Taxi Zone in which the taximeter was disengaged."

      - name: pickup_datetime
        data_type: timestamp
        description: "The date and time when the meter was engaged."

      - name: dropoff_datetime
        data_type: timestamp
        description: "The date and time when the meter was disengaged."

      - name: store_and_fwd_flag
        data_type: varchar
        description: "Flag indicating if the record was stored in vehicle memory before transmission."

      - name: passenger_count
        data_type: integer
        description: "The number of passengers in the vehicle reported by the driver."

      - name: trip_distance
        data_type: decimal(18,3)
        description: "The elapsed trip distance in miles reported by the taximeter."

      - name: fare_amount
        data_type: decimal(18,3)
        description: "The time-and-distance fare calculated by the meter."

      - name: extra
        data_type: decimal(18,3)
        description: "Miscellaneous extras and surcharges."

      - name: mta_tax
        data_type: decimal(18,3)
        description: "$0.50 MTA tax."

      - name: tip_amount
        data_type: decimal(18,3)
        description: "Tip amount (Credit card only)."

      - name: tolls_amount
        data_type: decimal(18,3)
        description: "Total amount of all tolls paid in trip."

      - name: improvement_surcharge
        data_type: decimal(18,3)
        description: "$0.30 improvement surcharge assessed at the point of hire."

      - name: total_amount
        data_type: decimal(18,3)
        description: "The total amount charged to passengers. Does not include cash tips."

      - name: payment_type
        data_type: integer
        description: "A numeric code signifying how the passenger paid (1= Credit card, 2= Cash, etc)."

  - name: stg_fhv_tripdata
    description: "Staging model for For-Hire Vehicle (FHV) trip data."
    columns:
      - name: dispatching_base_num
        data_type: varchar
        description: "The TLC Base License Number of the base that dispatched the trip."

      - name: pickup_location_id
        data_type: integer
        description: "TLC Taxi Zone in which the passenger was picked up."

      - name: dropoff_location_id
        data_type: integer
        description: "TLC Taxi Zone in which the passenger was dropped off."

      - name: pickup_datetime
        data_type: timestamp
        description: "The date and time of the pickup."

      - name: dropoff_datetime
        data_type: timestamp
        description: "The date and time of the dropoff."

      - name: sr_flag
        data_type: integer
        description: "Indicates if the trip was a shared ride (1 if yes, null or 0 if no)."

      - name: affiliated_base_number
        data_type: varchar
        description: "The TLC Base License Number of the base affiliated with the vehicle."