version: 2

models:
  - name: int_trips_unioned
    description: "Unioned green and yellow trip data with standardized column names and types."
    columns:
      - name: vendor_id
        data_type: integer
        description: "Code indicating the LPEP/TPEP provider (1= Creative Mobile Technologies, 2= VeriFone)."

      - name: rate_code_id
        data_type: integer
        description: "The final rate code in effect at the end of the trip."

      - name: pickup_location_id
        data_type: integer
        description: "TLC Taxi Zone ID where the meter was engaged."

      - name: dropoff_location_id
        data_type: integer
        description: "TLC Taxi Zone ID where the meter was disengaged."

      - name: pickup_datetime
        data_type: timestamp
        description: "The date and time when the meter was engaged."

      - name: dropoff_datetime
        data_type: timestamp
        description: "The date and time when the meter was disengaged."

      - name: store_and_fwd_flag
        data_type: varchar
        description: "Flag indicating if the trip record was held in vehicle memory (Y/N)."

      - name: passenger_count
        data_type: integer
        description: "Number of passengers in the vehicle (driver-entered)."

      - name: trip_distance
        data_type: decimal(18,3)
        description: "The elapsed trip distance in miles reported by the taximeter."

      - name: trip_type
        data_type: integer
        description: "1= Street-hail, 2= Dispatch (Specific to Green Taxis; NULL for Yellow)."

      - name: fare_amount
        data_type: decimal(18,3)
        description: "The time-and-distance fare calculated by the meter."

      - name: extra
        data_type: decimal(18,3)
        description: "Miscellaneous extras and surcharges (rush hour, overnight)."

      - name: mta_tax
        data_type: decimal(18,3)
        description: "$0.50 MTA tax."

      - name: tip_amount
        data_type: decimal(18,3)
        description: "Tip amount (Credit card payments only)."

      - name: tolls_amount
        data_type: decimal(18,3)
        description: "Total amount of all tolls paid."

      - name: ehail_fee
        data_type: decimal(18,3)
        description: "Fee for using e-hail service (usually NULL)."

      - name: improvement_surcharge
        data_type: decimal(18,3)
        description: "$0.30 improvement surcharge assessed on hailed trips."

      - name: total_amount
        data_type: decimal(18,3)
        description: "Total amount charged to passengers (excluding cash tips)."

      - name: payment_type
        data_type: integer
        description: "Numeric code for payment method (1= Credit card, 2= Cash, etc)."

      - name: service_type
        data_type: varchar
        description: "Identifies the source of the data ('green' or 'yellow')."

  - name: int_trips
    description: "Enriched trip data including a generated trip_id and descriptive payment types."
    columns:
      - name: trip_id
        data_type: varchar
        description: "Unique surrogate key generated for each trip."

      - name: vendor_id
        data_type: integer
        description: "Standardized vendor identifier."

      - name: service_type
        data_type: varchar
        description: "Source dataset identifier ('green' or 'yellow')."

      - name: rate_code_id
        data_type: integer
        description: "Final rate code in effect."

      - name: pickup_location_id
        data_type: integer
        description: "TLC Taxi Zone ID for pickup."

      - name: dropoff_location_id
        data_type: integer
        description: "TLC Taxi Zone ID for dropoff."

      - name: pickup_datetime
        data_type: timestamp
        description: "Timestamp of trip start."

      - name: dropoff_datetime
        data_type: timestamp
        description: "Timestamp of trip end."

      - name: store_and_fwd_flag
        data_type: varchar
        description: "Store and forward flag (Y/N)."

      - name: passenger_count
        data_type: integer
        description: "Passenger count reported by driver."

      - name: trip_distance
        data_type: decimal(18,3)
        description: "Miles traveled during the trip."

      - name: trip_type
        data_type: integer
        description: "Hail or Dispatch indicator."

      - name: fare_amount
        data_type: decimal(18,3)
        description: "Metered fare amount."

      - name: extra
        data_type: decimal(18,3)
        description: "Additional surcharges."

      - name: mta_tax
        data_type: decimal(18,3)
        description: "MTA tax amount."

      - name: tip_amount
        data_type: decimal(18,3)
        description: "Tip amount recorded (Credit card only)."

      - name: tolls_amount
        data_type: decimal(18,3)
        description: "Total tolls paid."

      - name: ehail_fee
        data_type: decimal(18,3)
        description: "e-hail service fee."

      - name: improvement_surcharge
        data_type: decimal(18,3)
        description: "Standardized improvement surcharge."

      - name: total_amount
        data_type: decimal(18,3)
        description: "Total trip cost."

      - name: payment_type
        data_type: integer
        description: "Numeric code signifying payment method."

      - name: payment_type_description
        data_type: varchar
        description: "Human-readable description of the payment_type (e.g., 'Credit card', 'Cash')."